kind: PersistentVolume
apiVersion: v1
metadata:
  name: elasticsearch-pv
  labels: 
    app: elasticsearch
    topology.kubernetes.io/region: us-east-1
    topology.kubernetes.io/zone: us-east-1b
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: "vol-09e7c2b5803e2ccb2"
    fsType: ext4
  storageClassName: aws-sc
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - us-east-1b
        - key: topology.kubernetes.io/region
          operator: In
          values:
          - us-east-1

