kind: PersistentVolume
apiVersion: v1
metadata:
  name: elasticsearch-pv
  labels: 
    app: elasticsearch
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: "vol-09e7c2b5803e2ccb2"
    fsType: ext4
  storageClassName: aws-sc
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
