apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-sc
provisioner: ebs.csi.aws.com
parameters: 
  type: gp3
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: WaitForFirstConsumer
# allowedTopologies:
# - matchLabelExpressions:
#   - key: failure-domain.beta.kubernetes.io/zone
#     values:
#     - ap-southeast-1a
#     - ap-southeast-1b
